name: Monitoring CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [dev]
env:
  ACTIONS_STEP_DEBUG: true

permissions:
  contents: read
  id-token: write

jobs:
  terraform-ci:
    name: Terraform Plan for Monitoring Infra
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::433331841346:role/Monitoring-role
          
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

      # - name: Run Infracost
      #   uses: infracost/actions/setup@v2
      #   with:
      #     api-key: ${{ secrets.INFRACOST_API_KEY }}
          
      # - name: Send Email(fail) 
      #   if: failure()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 587
      #     username: ${{ secrets.EMAIL_USERNAME }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     subject: "🚨 Monitoring CI Failed"
      #     to: yourteam@email.com
      #     from: Monitoring CI <your@email.com>
      #     body: "Terraform Plan or Validate failed. Please check the Actions log."

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - run: terraform init
      - run: terraform validate
      - run: terraform plan
