name: Monitoring CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  ACTIONS_STEP_DEBUG: true

permissions:
  contents: read
  id-token: write

jobs:
  terraform-ci:
    name: Terraform Plan for Monitoring Infra
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::502676416967:role/monitoring-role
          
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0


      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate
      - run: terraform plan

      - name: Run trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          hide-progress: true

