# .github/workflows/terraform-plan.yml
name: Terraform Plan

on:
  pull_request:
    branches: [main]
    paths:
      - 'operation-team-account/**'
      - 'identity-team-account/**'
      - 'prod-team-account/**'

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch origin/main
        run: git fetch origin main

      - name: Detect Changed Files
        id: detect
        run: |
          FILES=$(git diff --name-only origin/main..${{ github.sha }})
          echo "Changed files in PR:"
          echo "$FILES"
          
          if [ -z "$FILES" ]; then
            echo "No files changed. Skipping Terraform plan."
            exit 0
          fi

          if echo "$FILES" | grep -q '^operation-team-account/'; then
            DIR="operation-team-account"
          elif echo "$FILES" | grep -q '^identity-team-account/'; then
            DIR="identity-team-account"
          elif echo "$FILES" | grep -q '^prod-team-account/'; then
            DIR="prod-team-account"
          else
            echo "No matching folder changed."
            exit 1
          fi

          echo "$DIR" > changed_dir.txt
          echo "work_dir=$DIR" >> $GITHUB_OUTPUT

      - name: Upload Changed Dir as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-dir
          path: changed_dir.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          role-to-assume: ${{ secrets[format('ROLE_ARN_{0}', steps.detect.outputs.work_dir)] }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ steps.detect.outputs.work_dir }}

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ${{ steps.detect.outputs.work_dir }}
        continue-on-error: true
